version: '3.2'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  api:
    build: .
    ports:
      - "5000:5000"
    restart: on-failure
    depends_on: 
      - db
    environment:
      DB_HOST: db
    env_file: 
      - ./.env
    volumes:
      - ./src:/app/src

  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on: 
      - api