"""empty message

Revision ID: 5b3031a62788
Revises: 
Create Date: 2021-07-12 20:39:55.825510

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5b3031a62788"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "directors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("sername", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "genres",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("genre", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("genre"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("nick_name", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("pswhash", sa.String(length=100), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("nick_name"),
        sa.UniqueConstraint("pswhash"),
    )
    op.create_table(
        "films",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("release", sa.Date(), nullable=False),
        sa.Column("director_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("poster", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["director_id"],
            ["directors.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("poster"),
    )
    op.create_check_constraint("rating_check", "films", "rating >= 1 and rating  <= 10")
    op.create_table(
        "ref",
        sa.Column("films_id", sa.Integer(), nullable=False),
        sa.Column("genres_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["films_id"], ["films.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["genres_id"], ["genres.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("films_id", "genres_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ref")
    op.drop_table("films")
    op.drop_table("users")
    op.drop_table("genres")
    op.drop_table("directors")
    # ### end Alembic commands ###
