"""empty message

Revision ID: 70cf715fdf15
Revises: 7600cb4d6b3d
Create Date: 2021-07-16 10:33:52.753384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70cf715fdf15'
down_revision = '7600cb4d6b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('films', 'director_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('films', 'director_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
