"""empty message

Revision ID: 7600cb4d6b3d
Revises: 5b3031a62788
Create Date: 2021-07-16 10:31:44.326658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7600cb4d6b3d'
down_revision = '5b3031a62788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('films_director_id_fkey', 'films', type_='foreignkey')
    op.create_foreign_key(None, 'films', 'directors', ['director_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'films', type_='foreignkey')
    op.create_foreign_key('films_director_id_fkey', 'films', 'directors', ['director_id'], ['id'])
    # ### end Alembic commands ###
