"""empty message

Revision ID: d3d84141e1e6
Revises: 22b5fa3d4261
Create Date: 2021-07-06 22:05:46.698481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d84141e1e6'
down_revision = '22b5fa3d4261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('films_id', sa.Integer(), nullable=False),
    sa.Column('genres_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['films_id'], ['films.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genres_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('films_genre_id_fkey', 'films', type_='foreignkey')
    op.drop_column('films', 'genre_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('films_genre_id_fkey', 'films', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.drop_table('ref')
    # ### end Alembic commands ###
